/* Generated By:JJTree: Do not edit this line. ASTSQLExistsClause.java */

package com.hardcode.gdbms.parser;

public class ASTSQLExistsClause extends SimpleNode {
  public ASTSQLExistsClause(int id) {
    super(id);
  }

  public ASTSQLExistsClause(SQLEngine p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLEngineVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
