/* Generated By:JJTree: Do not edit this line. ASTSQLBetweenClause.java */

package com.hardcode.gdbms.parser;

public class ASTSQLBetweenClause extends SimpleNode {
  public ASTSQLBetweenClause(int id) {
    super(id);
  }

  public ASTSQLBetweenClause(SQLEngine p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLEngineVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
