/* Generated By:JJTree: Do not edit this line. ASTSQLIsClause.java */

package com.hardcode.gdbms.parser;

public class ASTSQLIsClause extends SimpleNode {
  public ASTSQLIsClause(int id) {
    super(id);
  }

  public ASTSQLIsClause(SQLEngine p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLEngineVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
