/* Generated By:JJTree: Do not edit this line. ASTSQLAndExpr.java */

package com.hardcode.gdbms.parser;

public class ASTSQLAndExpr extends SimpleNode {
  public ASTSQLAndExpr(int id) {
    super(id);
  }

  public ASTSQLAndExpr(SQLEngine p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SQLEngineVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
